/* Configuración de representantes. Edita este archivo para añadir/quitar reps.
   areas: nombre de estado ("Ohio") o subdividido ("Texas:north",
   "Florida:south", "California:south-west"). */
export const REPS = [
  {
    name: 'Martin Design Lines',
    contact: 'Doug Martin',
    company: '',
    email: 'doug@martindesignlines.com',
    phone: '214-725-2000',
    color: '#4a7c59',
    areas: ['Texas:north', 'Oklahoma', 'Arkansas', 'Louisiana:north'],
  },
  {
    name: 'CW Lighting, LLC',
    contact: '',
    company: '',
    email: 'info@cwlighting.com',
    phone: '713-690-9320',
    color: '#e58a3a',
    areas: ['Texas:south'],
  },
  {
    name: 'Stack Brogan Collective',
    contact: 'Diana Brogan',
    company: '',
    email: 'diana@stackbrogan.com',
    phone: '312-505-9884',
    color: '#c8a2d8',
    areas: ['Illinois', 'Wisconsin'],
  },
  {
    name: 'Facilitech Solutions',
    contact: 'Lisa Shumway',
    company: '',
    email: 'lisa@facilitechsolutions.com',
    phone: '248-330-0814',
    color: '#5aa2c9',
    areas: ['Michigan'],
  },
  {
    name: 'Power & Light Systems',
    contact: 'Abraham Benguigui',
    company: '',
    email: 'abenguigui@p-ls.com',
    phone: '',
    color: '#663399',
    areas: ['Florida:south'],
  },
  {
    name: 'MJ Solutions',
    contact: 'Scott McCoy',
    company: '',
    email: 'Scott@mjsreps.com',
    phone: '',
    color: '#7fc9b8',
    areas: ['Tennessee', 'Indiana', 'Kentucky', 'Florida:north'],
  },
  {
    name: 'ELA + Synergy',
    contact: 'Scott Prochazka',
    company: '',
    email: 'scott@electriclighting.com',
    phone: '',
    color: '#f7e6a2',
    areas: ['New York'],
  },
  {
    name: 'ELA + Synergy',
    contact: 'Laura Zimmerman',
    company: '',
    email: 'lauraz@ses95.com',
    phone: '',
    color: '#f7e6a2',
    areas: ['New Jersey', 'Pennsylvania'],
  },
  {
    name: 'Cait Solutions',
    contact: '',
    company: '',
    email: 'Caitlin@cait-solutions.com',
    phone: '',
    color: '#0f7e7e',
    areas: ['Ohio'],
  },
];

// Rep por defecto (cuando la búsqueda no coincide con ninguno).
export const DEFAULT_REP = {
  name: 'Indigoff',
  contact: '',
  company: '',
  email: 'info@indigoff.com',
  phone: '908-489-7323',
  color: '#7c6ce8',
  areas: [],
};

export const STATE_ALIASES = {
  tx: 'Texas', ca: 'California', ny: 'New York', fl: 'Florida',
  il: 'Illinois', wi: 'Wisconsin', mi: 'Michigan', oh: 'Ohio',
  tn: 'Tennessee', in: 'Indiana', ky: 'Kentucky', ok: 'Oklahoma',
  ar: 'Arkansas', la: 'Louisiana', nj: 'New Jersey', pa: 'Pennsylvania',
  al: 'Alabama', or: 'Oregon', wa: 'Washington', nm: 'New Mexico',
  ga: 'Georgia', nc: 'North Carolina', sc: 'South Carolina', va: 'Virginia',
  wv: 'West Virginia', md: 'Maryland', de: 'Delaware', ct: 'Connecticut',
  ma: 'Massachusetts', ri: 'Rhode Island', nh: 'New Hampshire', vt: 'Vermont',
  me: 'Maine', ak: 'Alaska', hi: 'Hawaii', az: 'Arizona', co: 'Colorado',
  ut: 'Utah', nv: 'Nevada', id: 'Idaho', mt: 'Montana', wy: 'Wyoming',
  nd: 'North Dakota', sd: 'South Dakota', ne: 'Nebraska', ks: 'Kansas',
  mo: 'Missouri', ia: 'Iowa', mn: 'Minnesota', ms: 'Mississippi',
};

export const STATES = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
  'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
  'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
  'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
  'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina',
  'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
  'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
  'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming',
];

export const DIRECTIONS = {
  north: { key: 'north', label: 'North' },
  northern: { key: 'north', label: 'Northern' },
  n: { key: 'north', label: 'N.' },
  south: { key: 'south', label: 'South' },
  southern: { key: 'south', label: 'Southern' },
  s: { key: 'south', label: 'S.' },
  east: { key: 'east', label: 'East' },
  eastern: { key: 'east', label: 'Eastern' },
  e: { key: 'east', label: 'E.' },
  west: { key: 'west', label: 'West' },
  western: { key: 'west', label: 'Western' },
  w: { key: 'west', label: 'W.' },
  northeast: { key: 'north-east', label: 'Northeast' },
  northeastern: { key: 'north-east', label: 'Northeastern' },
  ne: { key: 'north-east', label: 'NE' },
  northwest: { key: 'north-west', label: 'Northwest' },
  northwestern: { key: 'north-west', label: 'Northwestern' },
  nw: { key: 'north-west', label: 'NW' },
  southeast: { key: 'south-east', label: 'Southeast' },
  southeastern: { key: 'south-east', label: 'Southeastern' },
  se: { key: 'south-east', label: 'SE' },
  southwest: { key: 'south-west', label: 'Southwest' },
  southwestern: { key: 'south-west', label: 'Southwestern' },
  sw: { key: 'south-west', label: 'SW' },
};
